### ISSUE TITLE
Question: can one study Hubbard models with this

### ISSUE THREAD

**Issue by jeffhammond** [twesterhout/spin-ed#4]
I apologize for the naive question, but can this package support Hubbard Hamiltonians or not?  Thanks.

**Comment by twesterhout** [comment]
There is currently no native support for fermionic models. One could map the fermionic Hamiltonian to a spin-1/2 one, but all information about symmetries would (likely) be lost. First, this is quite tedious work and as such not very user-friendly. Secondly, loosing information about symmetries would greatly reduce the size of systems which can be tackled.
So I'd say that right now there is no support for Hubbard models, but I have some ideas about potential implementation of fermionic bases, so this feature might be added in the future.

**Comment by jeffhammond** [comment]
Thanks for the info.  I am really rusty on this topic.  I looked at Hubbard a lot many years ago and saw t-J, etc. in the literature but apparently forgot the higher order bit of which ones were fermionic versus bosonic.
