### ISSUE TITLE
Change interaction axis

### ISSUE THREAD

**Issue by lynkeryn** [twesterhout/spin-ed#5]
I have a SpinED file and a .yaml file where I define an Ising model for a system of n spins (see attachments). At this point, the interactions between the spins are directed along the Z-axis, and the magnetic field along the X-axis.
I need to change these axes, that is, so that the interaction is along the X-axis, and the magnetic field is along the Z-axis.
How to do it?
[ising_16.zip](https://github.com/twesterhout/spin-ed/files/11522935/ising_16.zip)

**Comment by twesterhout** [comment]
Hello @lynkeryn, it seems that your Hamiltonian consists of Z⊗Z and X terms. You can similarly write it using X⊗X and Z terms. For instance:
![image](https://github.com/twesterhout/spin-ed/assets/14264576/d8f73135-756e-49a8-80d2-7144e35ae4e1)
You can then just plug the new matrices into SpinED.

**Comment by lynkeryn** [comment]
> Hello @lynkeryn, it seems that your Hamiltonian consists of Z⊗Z and X terms. You can similarly write it using X⊗X and Z terms. For instance: ![image](https://user-images.githubusercontent.com/14264576/239842359-d8f73135-756e-49a8-80d2-7144e35ae4e1.png) You can then just plug the new matrices into SpinED.

And accordingly, for the magnetic field, I need to substitute the Pauli Z matrix instead of the Pauli X matrix?

**Comment by twesterhout** [comment]
Yes, exactly. This is your standard Kramers-Wannier duality for the 1D Ising model.

**Comment by lynkeryn** [comment]
> Yes, exactly. This is your standard Kramers-Wannier duality for the 1D Ising model.

Okay, this should help. Thank you!
